/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/departments/details` | `/departments/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(app)'}/departments/[id]` | `/departments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/departments/[id]/tasks` | `/departments/[id]/tasks`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/departments/[id]/tasks/[id]` | `/departments/[id]/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number;id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/departments/details` | `/departments/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(app)'}/departments/[id]` | `/departments/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/departments/[id]/tasks` | `/departments/[id]/tasks`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/departments/[id]/tasks/[id]` | `/departments/[id]/tasks/[id]`, params: Router.UnknownOutputParams & { id: string;id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/departments/details${`?${string}` | `#${string}` | ''}` | `/departments/details${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/departments/details` | `/departments/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/departments/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/departments/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/departments/${Router.SingleRoutePart<T>}/tasks${`?${string}` | `#${string}` | ''}` | `/departments/${Router.SingleRoutePart<T>}/tasks${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/departments/${Router.SingleRoutePart<T>}/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/departments/${Router.SingleRoutePart<T>}/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(app)'}/departments/[id]` | `/departments/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/departments/[id]/tasks` | `/departments/[id]/tasks`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/departments/[id]/tasks/[id]` | `/departments/[id]/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number;id: string | number; } };
    }
  }
}
